/**
 * Generate content/seo/youtube.md: the title, description and chapters each YouTube video
 * should carry so YouTube (a top answer-engine source) mirrors and links back to the site.
 * Usage: pnpm youtube:metadata
 */
import { writeFileSync } from "node:fs";
import { readJson, readMarkdownDir } from "../../src/lib/content/files";
import type { EpisodeMeta } from "../../src/lib/content/schema";

const SITE = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://buildwithbob.vercel.app"
).replace(/\/$/, "");

const stamp = (s: number) => {
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = String(s % 60).padStart(2, "0");
  return h ? `${h}:${String(m).padStart(2, "0")}:${sec}` : `${m}:${sec}`;
};

const posts = readMarkdownDir("content/episodes");
const sections = readJson<EpisodeMeta[]>("data/episodes.json").flatMap((meta) => {
  const post = posts.find((p) => p.data.videoId === meta.videoId);
  if (!post) return [];
  const chapters = (
    meta.chapters.length ? meta.chapters : (post.data.chapters ?? [])
  ) as {
    start: number;
    title: string;
  }[];
  const url = `${SITE}/episodes/${meta.slug}`;
  const description = [
    String(post.data.tldr),
    "",
    `📖 Full write-up, key takeaways, FAQ and searchable transcript: ${url}`,
    `🧰 Project: ${SITE}/projects/${meta.project}`,
    "",
    ...chapters.map((c) => `${stamp(c.start)} ${c.title}`),
    "",
    `Building with Bob: Tejas Kumar and David Jones-Gilardi build open-source apps live with IBM Bob. ${SITE}`,
  ].join("\n");
  return [
    [
      `## Episode ${meta.number}: https://www.youtube.com/watch?v=${meta.videoId}`,
      "",
      `- **Current title:** ${meta.youtubeTitle}`,
      `- **New title:** Building with Bob #${meta.number}: ${post.data.title}`,
      "",
      "```text",
      description,
      "```",
      "",
    ].join("\n"),
  ];
});

writeFileSync(
  "content/seo/youtube.md",
  `# YouTube metadata to apply\n\nGenerated by \`pnpm youtube:metadata\` from the site's own titles and chapters. Apply in YouTube Studio so every video mirrors and links back to its page.\n\n${sections.join("\n")}`,
);
console.log(`Wrote content/seo/youtube.md (${sections.length} videos)`);
